services:
  python_service:
#    image: python:latest
    build:
      context: ./docker/python
    ports:
      - 9999:9999/udp
    volumes:
      - .:/app
    command: python -u ./app/server.py 9999
